### ISSUE TITLE
Dependancy on garethr/docker (>=5.1.0)  - Deprecated package

### ISSUE THREAD

**Issue by lastusrnameon3** [puppetlabs/pltraining-dockeragent#56]
garethr/docker (>=5.1.0)  is deprecated as of 2 months ago.

**Comment by greglarkin** [comment]
Thank you for opening the issue, and my apologies for the delay in responding. We are working on upgrading the module to use the puppetlabs/docker module and have a PR open at the moment. Once we've tested on this end, we'll plan to merge it.

Are you actively using this Puppet module?

**Comment by greglarkin** [comment]
Resolved with version 0.0.17
